# Homework 1 - Jaime Juárez . MlZoomcamp - 2026

In [1]:
import numpy as np
import pandas as pd

In [2]:
print(pd.__version__)
#print(np.__version__)

3.0.5


In [3]:
url="https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
# Load directly into memory
df = pd.read_csv(url)

# Save a local copy (optional)
#df.to_csv("car_fuel_efficiency.csv", index=False)

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [4]:
#How many records are in the dataset?
len(df["engine_displacement"])

10000

In [5]:
#How many fuel types are presented in the dataset?
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [6]:
#How many columns in the dataset have missing values?
len(df.columns[df.isnull().any()])

2

In [7]:
#What's the maximum fuel efficiency of cars from Asia?
df[df["origin"]=="Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [8]:
# Find the median value of the horsepower column in the dataset.
# Next, calculate the most frequent value of the same horsepower column.
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.
# Has it changed?
print("median value df horsepower:", df["horsepower"].median())
print("most frequent value:", df["horsepower"].mode()[0])
print("all na values has been filled with most frequent value")
df_2=df.fillna(df["horsepower"].mode()[0])
print("new median value df2 horsepower",df_2["horsepower"].median())
print("R// yes, it decreased")

median value df horsepower: 254.0
most frequent value: 252.0
all na values has been filled with most frequent value
new median value df2 horsepower 252.0
R// yes, it decreased


In [9]:
print(df.head(2))
print(df.columns.tolist())

   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4   
1        2008  Europe    Diesel  Front-wheel drive          4   

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2180              6       243.0            3870   
1                 2390              6       272.0            4210   

   acceleration  fuel_efficiency_mpg  
0           NaN                 31.9  
1           NaN                 31.3  
['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg']


In [10]:
#Select all the cars from Asia
#Select only columns vehicle_weight and model_year
#Select the first 7 values
#Get the underlying NumPy array. Let's call it X.
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#Invert XTX.
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#What's the sum of all the elements of the result?X
df_3=df[df["origin"]=="Asia"][["vehicle_weight","model_year"]].head(7)
X=df[df["origin"]=="Asia"][["vehicle_weight","model_year"]].head(7).to_numpy()

In [11]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [12]:
X_T = X.T

In [13]:
XTX = np.dot(X.T, X)

In [14]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [15]:
 np.dot(XTX_inv, XTX)

array([[ 1.00000000e+00, -7.77917769e-15],
       [-8.75935812e-14,  1.00000000e+00]])

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [17]:
w= np.dot(np.dot(XTX_inv, X_T),y)

In [18]:
print(f"R// La respuesta es  {w.sum()} del problema" )

R// La respuesta es  0.36919696904925486 del problema
